compatibility_date = "2022-01-20"
name = "rustwasm-markdown-parser"
main = "build/worker/shim.mjs"
workers_dev = true
send_metrics = false

[vars]
WORKERS_RS_VERSION = "0.0.16"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

